package spec

// DESADV message specification.
var (
	DESADV = Msg("DESADV",
		S("UNA", C, 1),
		S("UNB", C, 1),
		S("UNH", M, 1),
		S("BGM", M, 1),
		S("DTM", C, 10),
		S("ALI", C, 5),
		S("MEA", C, 5),
		S("MOA", C, 5),
		SG("SG1", C, 10,
			S("RFF", M, 1),
			S("DTM", C, 1),
		),
		SG("SG2", C, 99,
			S("NAD", M, 1),
			S("LOC", C, 10),
			SG("SG3", C, 10,
				S("RFF", M, 1),
			),
			SG("SG4", C, 10,
				S("CTA", M, 1),
				S("COM", C, 5),
			),
		),
		SG("SG5", C, 10,
			S("TOD", M, 1),
			S("LOC", C, 5),
		),
		SG("SG6", C, 10,
			S("TDT", M, 1),
			SG("SG7", C, 10,
				S("LOG", M, 1),
				S("DTM", C, 10),
			),
		),
		SG("SG8", C, 10,
			S("EQD", M, 1),
			S("MEA", C, 5),
			S("SEL", C, 5),
		),
	)
)
