package spec

var orders = Msg("ORDERS",
	S("UNA", C, 1),
	S("UNB", C, 1),
	S("UNH", M, 1),
	S("BGM", M, 1),
	S("DTM", C, 35),
	S("PAI", C, 1),
	S("ALI", C, 5),
	S("IMD", C, 1),
	S("FTX", C, 99),
	SG("SG1", C, 10,
		S("RFF", M, 1),
		S("DTM", C, 5),
	),
	SG("SG2", C, 99,
		S("NAD", M, 1),
		S("LOC", C, 25),
		S("FII", C, 5),
		SG("SG3", C, 10,
			S("RFF", M, 1),
			S("DTM", C, 5),
		),
		SG("SG4", C, 5,
			S("DOC", M, 1),
			S("DTM", C, 5),
		),
		SG("SG5", C, 5,
			S("CTA", M, 1),
			S("COM", C, 5),
		),
	),
	SG("SG6", C, 5,
		S("TAX", M, 1),
		S("MOA", C, 1),
		S("LOC", C, 5),
	),
	SG("SG7", C, 5,
		S("CUX", M, 1),
		S("PCD", C, 5),
		S("DTM", C, 5),
	),
	SG("SG8", C, 10,
		S("PAT", M, 1),
		S("DTM", C, 5),
		S("PCD", C, 1),
		S("MOA", C, 1),
	),
	SG("SG9", C, 10,
		S("TDT", M, 1),
		SG("SG10", C, 10,
			S("LOC", M, 1),
			S("DTM", C, 5),
		),
	),
	SG("SG11", C, 5,
		S("TOD", M, 1),
		S("LOC", C, 5),
	),
	SG("SG12", C, 10,
		S("PAC", M, 1),
		S("MEA", C, 5),
		SG("SG13", C, 5,
			S("PCI", M, 1),
			S("RFF", C, 1),
			S("DTM", C, 5),
			S("GIN", C, 10),
		),
	),
	SG("SG14", C, 10,
		S("EQD", M, 1),
		S("HAN", C, 5),
		S("MEA", C, 5),
		S("FTX", C, 5),
	),
	SG("SG15", C, 10,
		S("SCC", M, 1),
		S("FTX", C, 5),
		S("RFF", C, 5),
		SG("SG16", C, 10,
			S("QTY", M, 1),
			S("DTM", C, 5),
		),
	),
	SG("SG17", C, 25,
		S("APR", M, 1),
		S("DTM", C, 5),
		S("RNG", C, 1),
	),
	SG("SG18", C, 15,
		S("ALC", M, 1),
		S("ALI", C, 5),
		S("DTM", C, 5),
		SG("SG19", C, 1,
			S("QTY", M, 1),
			S("RNG", C, 1),
		),
		SG("SG20", C, 1,
			S("PCD", M, 1),
			S("RNG", C, 1),
		),
		SG("SG21", C, 2,
			S("MOA", M, 1),
			S("RNG", C, 1),
		),
		SG("SG22", C, 1,
			S("RTE", M, 1),
			S("RNG", C, 1),
		),
		SG("SG23", C, 5,
			S("TAX", M, 1),
			S("MOA", C, 1),
		),
	),
	SG("SG24", C, 100,
		S("RCS", M, 1),
		S("RFF", C, 5),
		S("DTM", C, 5),
		S("FTX", C, 5),
	),
	SG("SG25", C, 200000,
		S("LIN", M, 1),
		S("PIA", C, 25),
		S("IMD", C, 99),
		S("MEA", C, 5),
		S("QTY", C, 10),
		S("PCD", C, 5),
		S("ALI", C, 5),
		S("DTM", C, 35),
		S("MOA", C, 10),
		S("GIN", C, 1000),
		S("GIR", C, 1000),
		S("QVR", C, 1),
		S("DOC", C, 5),
		S("PAI", C, 1),
		S("FTX", C, 99),
		SG("SG26", C, 999,
			S("CCI", M, 1),
			S("CAV", C, 10),
			S("MEA", C, 10),
		),
		SG("SG27", C, 10,
			S("PAT", M, 1),
			S("DTM", C, 5),
			S("PCD", C, 1),
			S("MOA", C, 1),
		),
		SG("SG28", C, 25,
			S("PRI", M, 1),
			S("CUX", C, 1),
			S("APR", C, 1),
			S("RNG", C, 1),
			S("DTM", C, 5),
		),
		SG("SG29", C, 10,
			S("RFF", M, 1),
			S("DTM", C, 5),
		),
		SG("SG30", C, 10,
			S("PAC", M, 1),
			S("MEA", C, 5),
			S("QTY", C, 5),
			S("DTM", C, 5),
			SG("SG31", C, 1,
				S("RFF", M, 1),
				S("DTM", C, 5),
			),
			SG("SG32", C, 5,
				S("PCI", M, 1),
				S("RFF", C, 1),
				S("DTM", C, 5),
				S("GIN", C, 10),
			),
		),
		SG("SG33", C, 9999,
			S("LOC", M, 1),
			S("QTY", C, 1),
			S("DTM", C, 5),
		),
		SG("SG34", C, 10,
			S("TAX", M, 1),
			S("MOA", C, 1),
			S("LOC", C, 5),
		),
		SG("SG35", C, 99,
			S("NAD", M, 1),
			S("LOC", C, 5),
			SG("SG36", C, 5,
				S("RFF", M, 1),
				S("DTM", C, 5),
			),
			SG("SG37", C, 5,
				S("DOC", M, 1),
				S("DTM", C, 5),
			),
			SG("SG38", C, 5,
				S("CTA", M, 1),
				S("COM", C, 5),
			),
		),
		SG("SG39", C, 99,
			S("ALC", M, 1),
			S("ALI", C, 5),
			S("DTM", C, 5),
			SG("SG40", C, 1,
				S("QTY", M, 1),
				S("RNG", C, 1),
			),
			SG("SG41", C, 2,
				S("PCD", M, 1),
				S("RNG", C, 1),
			),
			SG("SG42", C, 1,
				S("MOA", M, 1),
				S("RNG", C, 1),
			),
			SG("SG43", C, 1,
				S("RTE", M, 1),
				S("RNG", C, 1),
			),
			SG("SG44", C, 5,
				S("TAX", M, 1),
				S("MOA", C, 1),
			),
		),
	),
	SG("SG45", C, 10,
		S("TDT", M, 1),
		SG("SG46", C, 10,
			S("LOC", M, 1),
			S("DTM", C, 5),
		),
	),
	SG("SG47", C, 5,
		S("TOD", M, 1),
		S("LOC", C, 2),
	),
	SG("SG48", C, 10,
		S("EQD", M, 1),
		S("HAN", C, 5),
		S("MEA", C, 5),
		S("FTX", C, 5),
	),
	SG("SG49", C, 100,
		S("SCC", M, 1),
		S("FTX", C, 5),
		S("RFF", C, 5),
		SG("SG50", C, 10,
			S("QTY", M, 1),
			S("DTM", C, 5),
		),
	),
	SG("SG51", C, 100,
		S("RCS", M, 1),
		S("RFF", C, 5),
		S("DTM", C, 5),
		S("FTX", C, 5),
	),
	SG("SG52", C, 100,
		S("STG", M, 1),
		SG("SG53", C, 3,
			S("QTY", M, 1),
			S("MOA", C, 1),
		),
	),
	S("UNS", C, 1),
	S("MOA", C, 12),
	S("CNT", C, 5),
	SG("SG54", C, 10,
		S("ALC", M, 1),
		S("ALI", C, 1),
		S("MOA", C, 2),
	),
	S("UNT", M, 1),
	S("UNZ", C, 1),
)

func init() {
	Add("ORDERS", orders)
}
